name: PHP 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: my-label

    steps:
    - uses: actions/checkout@v2

    - name: Validate php.json and php.lock
      run: php validate --strict

    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.16.0

      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/php.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: php install --prefer-dist --no-progress

    # Add a test script to php.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getphp.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: php run-script test
